name: hello-world
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build steps
        run: echo "hello, ${{ vars.MY_NAME }}, this is variable"
        run: echo "my dirty secret is ${{ secrets.MY_DIRTY_SECRET }}"
