name: hello-world
on: workflow_dispatch
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello
        run: |
        echo "hello to the github action world"
        echo "this is multi line practice"
