name: context variable or build in github action variable
on: push
jobs:
  context-variable-demo:
    runs-on: ubuntu-latest
    steps:
      - name: context variable
        run: |
          echo "this workflow is triggered by ${{ github.actor }}"
          echo "the repo name is ${{ github.repository }}"
