name: job level if conditon
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "this is build job"
