name: output demo
on: push
jobs:
  job1: 
    outputs:
      version: ${{steps.step1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step1
        run: echo  "version=2.2.2" >> $GITHUB_OUTPUT
      
      - name: step two
        run: echo "this version is from step one ${{ steps.step1.outputs.version }}"
  job2:
    needs: job1
    runs-on: utuntu-latest
    steps:
      - name: job2 step one
        run: echo "this is the verion from job ouput ${{needs.job1.outputs.version}}"

